# Generated by Django 3.1.8 on 2021-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
        migrations.AddField(
            model_name='casa',
            name='area_construida',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='casa',
            name='area_lote',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='casa',
            name='baños',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casa',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='casa',
            name='habitaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casa',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='casa',
            name='ubicacion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='casa',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
